fix: categoryName 필드 category 필드명으로 변경
ssu-student-union/homepage-frontend pull request #362
Opened 2024-12-10 05:33 UTC by dvp-tae

## 1️⃣ 작업 내용 Summary

- resolved #361

### 기존 코드에 영향을 미치지 않는 변경사항

### 기존 코드에 영향을 미치는 변경사항

PostDetailResDto 타입 중 categoryName -> category 로 변경
PostPetitionDetailPostSection.tsx 타입 변경 적용
useAuditPatch.ts useLostPatch.ts usePartenership.ts 타입 변경 적용

### 버그 픽스

### ✚ 피그마

### ✚ 관련 문서

## 2️⃣ 리뷰어에게..

## 3️⃣ 추후 작업할 내용

## 4️⃣ 체크리스트

- [ ] `main` 브랜치의 최신 코드를 `pull` 받았나요?

2024-12-10 05:48 UTC, EATSTEAK requested changes
https://github.com/ssu-student-union/homepage-frontend/blob/285c4e7e69915ade199be440e4bcc11438c8c720/src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx#L38

이거 LocalStorage에 들어있다가 나온거여서 any네요. 한번 확인해보셔야 할 듯

2024-12-10 12:48 UTC, jongse7 approved these changes

2024-12-10 12:48 UTC, jongse7 commented on src/pages/petition-notice/[id]/containers/PostPetitionDetailPostSection.tsx
> +                <StateTag current={data?.data.postDetailResDto.category || null} />
아이고 다 고쳐주시다니 고생하셨습니다

2024-12-10 14:01 UTC, EATSTEAK requested changes

2024-12-10 14:01 UTC, EATSTEAK commented on src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
> +      const postDetailResDto = parsedContent.data.postDetailResDto;
```suggestion
      const postDetailResDto = parsedContent.postDetailResDto;
```

2024-12-10 14:01 UTC, EATSTEAK commented on src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
> +        postId: Number(parsedContent.data.postDetailResDto.postId),
```suggestion
        postId: Number(parsedContent.postDetailResDto.postId),
```

2024-12-10 14:01 UTC, EATSTEAK commented on src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
> +          const old_c = parsedContent.data.postDetailResDto.content;
```suggestion
          const old_c = parsedContent.postDetailResDto.content;
```

2024-12-10 14:02 UTC, EATSTEAK commented on src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
> +      const postDetailResDto = parsedContent.data.postDetailResDto;
```suggestion
      const postDetailResDto = parsedContent.postDetailResDto;
```

2024-12-10 14:12 UTC, dvp-tae commented on src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
> +  const parsedContent = JSON.parse(oldContent) as GetBoardDetailResponse;
아 맞네요.. 요고 수정해서 다시 올릴게요 꼼꼼히 봐주셔서 감사합니당👍

2024-12-11 07:08 UTC, EATSTEAK approved these changes
LGTM 👍 고생하셨습니다.

2024-12-11 10:24 UTC, merged